# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1429713842);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1429713962);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1429714344);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1429713721);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1429710624);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 327680);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 26);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.introShown", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "CN");
user_pref("browser.search.region", "CN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150306140238");
user_pref("browser.slowStartup.averageTime", 26392);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20150306140238");
user_pref("browser.startup.homepage_override.mstone", "36.0.1");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":3}");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button-throttled\",\"loop-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\",\"addon-bar\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1429713472911");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1429713477940");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1429799877940");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1426688209805");
user_pref("datareporting.policy.firstRunTime", "1426685228196");
user_pref("datareporting.sessions.current.activeTicks", 171);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 14606);
user_pref("datareporting.sessions.current.main", 968);
user_pref("datareporting.sessions.current.sessionRestored", 21308);
user_pref("datareporting.sessions.current.startTime", "1429710497290");
user_pref("datareporting.sessions.current.totalTime", 6549);
user_pref("datareporting.sessions.currentIndex", 19);
user_pref("datareporting.sessions.prunedIndex", 18);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 6);
user_pref("extensions.blocklist.pingCountVersion", 5);
user_pref("extensions.bootstrappedAddons", "{\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"36.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-zh-CN@firefox.mozilla.org\":{\"version\":\"36.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-zh-CN@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"36.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"webapps-team@lists.launchpad.net\":{\"version\":\"3.0.2\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.0,%7B2e1445b0-2682-11e1-bfc2-0800200c9a66%7D:2014.08.06.beta,online-accounts%40lists.launchpad.net:0.5,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:36.0.1");
user_pref("extensions.getAddons.cache.lastUpdate", 1429713845);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.hotfix.lastVersion", "20150402.01");
user_pref("extensions.lastAppVersion", "36.0.1");
user_pref("extensions.lastPlatformVersion", "36.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"36.0.1\",\"st\":1425652039000},\"langpack-zh-CN@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-zh-CN@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"36.0.1\",\"st\":1425652222000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":false,\"v\":\"36.0.1\",\"st\":1425652039000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"35.0.1\",\"st\":1426690420000,\"mt\":1425651385000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1424289188000,\"mt\":1420839872000},\"{2e1445b0-2682-11e1-bfc2-0800200c9a66}\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/{2e1445b0-2682-11e1-bfc2-0800200c9a66}\",\"e\":true,\"v\":\"2014.08.06.beta\",\"st\":1424289188000,\"mt\":1407283796000},\"webapps-team@lists.launchpad.net\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/webapps-team@lists.launchpad.net\",\"e\":true,\"v\":\"3.0.2\",\"st\":1424289189000,\"mt\":1397665356000}},\"app-system-local\":{\"online-accounts@lists.launchpad.net\":{\"d\":\"/usr/lib/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/online-accounts@lists.launchpad.net\",\"e\":true,\"v\":\"0.5\",\"st\":1424289189000,\"mt\":1390969638000}}}");
user_pref("gecko.buildID", "20150306140238");
user_pref("gecko.mstone", "36.0.1");
user_pref("idle.lastDailyNotification", 1429715320);
user_pref("media.gmp-gmpopenh264.lastUpdate", 1426688216);
user_pref("media.gmp-gmpopenh264.version", "1.3");
user_pref("media.gmp-manager.lastCheck", 1429627035);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.http.atsvc.enabled", false);
user_pref("network.http.atsvc.oe", false);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1429713473);
user_pref("places.history.expiration.transient_current_max_pages", 26309);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1429715320);
user_pref("toolkit.startup.last_success", 1429710498);
user_pref("toolkit.telemetry.previousBuildID", "20150306140238");
